---

#ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q skymind@52.170.5.39"'

jenkins_master_number_of_executors: 0
jenkins_master_persistent_store_mount: "/datadrive"
jenkins_master_temporary_store_mount: "/mnt"
jenkins_master_home_folder_path: "{{ jenkins_master_persistent_store_mount }}/jenkins_home"
jenkins_master_docker_folder_path: "/home/{{ jenkins_user_name }}/docker"
jenkins_master_workspace_folder_path: "{{ jenkins_master_temporary_store_mount }}/jenkins_workspace"
jenkins_master_container_workspace_path: "/var/jenkins_workspace"
jenkins_master_plugins_list_name: "plugins_custom.txt"

docker_ce_version: "17.12.1~ce-0~ubuntu"
docker_ce_prerequisite_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
docker_ce_repository_url: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
docker_ce_repository_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_ce_repository_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_ce_group_members:
  - "{{ ansible_user }}"
  - "{{ jenkins_user_name }}"

docker_compose_version: ''

system_packages:
  - python-setuptools
  - python-dev
  - python-pip
  - python3-lxml
  - python3-setuptools
  - python3-pip
  - build-essential

# Used in roles/jenkins-master/templates/docker/init.groovy.d/jenkins_master_config.groovy
jenkins_sonar_server_auth_token: "{{ vault_jenkins_sonar_server_auth_token }}"
jenkins_smtp_auth_password: "{{ vault_jenkins_smtp_auth_password }}"

# Used in roles/jenkins-master/templates/docker/init.groovy.d/jenkins_master_credentials_config.groovy
jenkins_github_machine_user_token: "{{ vault_jenkins_github_machine_user_token }}"

# Used in roles/jenkins-master/templates/docker/init.groovy.d/jenkins_master_security_config.groovy
jenkins_github_security_realm_client_id: "{{ vault_jenkins_github_security_realm_client_id }}"
jenkins_github_security_realm_client_secret: "{{ vault_jenkins_github_security_realm_client_secret }}"
jenkins_github_security_realm_oauth_scopes: "{{ vault_jenkins_github_security_realm_oauth_scopes }}"
jenkins_admin_user_names: "{{ vault_jenkins_admin_user_names }}"
jenkins_organization_names: "{{ vault_jenkins_organization_names }}"