---
# handlers file for jenkins-slave

- name: Restart tinc service
  command: "{{ item }}"
  with_items:
    - "launchctl unload -w {{ tinc_service_config_file_path }}/{{ tinc_service_config_file_name }}"
    - "launchctl load -w {{ tinc_service_config_file_path }}/{{ tinc_service_config_file_name }}"
  become: true
  when: ansible_os_family == "Darwin"

- name: Restart Jenkins slave service
  command: "{{ item }}"
  with_items:
    - "launchctl unload -w {{ jenkins_slave_service_config_file_path }}/{{ jenkins_slave_service_config_file_name }}"
    - "launchctl load -w {{ jenkins_slave_service_config_file_path }}/{{ jenkins_slave_service_config_file_name }}"
  become: true
  when: ansible_os_family == "Darwin"

- name: Restart Jenkins slave
  command: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for Jenkins slave restart
  local_action:
    module: wait_for
    host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
    port: 22
    delay: 10
  become: no