version: '3.3'
services:
  skil-build:
    build:
      context: ./docker/${OS_NAME}
      dockerfile: ./Dockerfile
      args:
        SKIL_BASE_IMAGE_NAME: ${SKIL_BASE_IMAGE_NAME}
        SKIL_VERSION: ${SKIL_VERSION}
        SKIL_DOCKER_IMAGE_REVISION: ${SKIL_DOCKER_IMAGE_REVISION}
        GIT_COMMIT: ${GIT_COMMIT}
    image: skil:${SKIL_VERSION}-${SKIL_DOCKER_IMAGE_TAG}
    container_name: skil_server
    ports:
    # DL4J UI first port
    - "8080:8080"
    # PLD port
    - "9008:9008"

#  skil-centos:
#    build:
#      context: ./docker/centos
#      dockerfile: ./Dockerfile
#      args:
#        SKIL_BASE_IMAGE_NAME: ${SKIL_CENTOS_BASE_IMAGE_NAME}
#        SKIL_VERSION: ${SKIL_VERSION}
#        SKIL_DOCKER_IMAGE_REVISION: ${SKIL_DOCKER_IMAGE_REVISION_NUMBER}
#    image: skil:${SKIL_VERSION}-${SKIL_CENTOS_DOCKER_IMAGE_TAG}
#    container_name: skil_server
#    ports:
#    # DL4J UI first port
#    - "8080:8080"
#    # PLD port
#    - "9008:9008"
#  skil-ubuntu:
#    build:
#      context: ./docker/ubuntu
#      dockerfile: ./Dockerfile
#      args:
#        SKIL_BASE_IMAGE_NAME: ${SKIL_UBUNTU_BASE_IMAGE_NAME}
#        SKIL_VERSION: ${SKIL_VERSION}
#        SKIL_DOCKER_IMAGE_REVISION: ${SKIL_DOCKER_IMAGE_REVISION_NUMBER}
#    image: skil:${SKIL_VERSION}-${SKIL_UBUNTU_DOCKER_IMAGE_TAG}
#    container_name: skil_server
#    ports:
#    # DL4J UI first port
#    - "8080:8080"
#    # PLD port
#    - "9008:9008"
