---
- include_vars: swap_vars.yml

- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }}
  args:
    creates: "{{ swap_file_path }}"

- name: Change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600

- name: Make swap file
  command: "mkswap {{ swap_file_path }}"
  args:
    creates: "{{ swap_file_path }}"

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  args: 
    creates: "{{ swap_file_path }}"

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    sysctl_set: yes
    state: present

- name: Set cache
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ cache_value }}"
    sysctl_set: yes
    state: present
  