Vagrant.configure(2) do |config|
    config.vm.define "master", autostart: false do |master|
        master.vm.box = "ubuntu/xenial64"
        master.vm.hostname = "jenkins-master"

        master.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
        master.vm.network "private_network", ip: "172.16.0.10"

        master.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
            v.customize ["modifyvm", :id, "--name", "jenkis-master"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end

    config.vm.define "slave" do |slave|
        slave.vm.box = "ubuntu/xenial64"
        slave.vm.hostname = "jenkins-slave"

        slave.vm.network "private_network", ip: "172.16.0.20"

        slave.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
            v.customize ["modifyvm", :id, "--name", "jenkis-slave"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end
end