---
# tasks file for common

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/main.yml"

- name: Create Jenkins user group
  group:
    name: "{{ jenkins_user_group }}"
  tags:
    - provision-jenkins

- name: Create Jenkins user
  user:
    name: "{{ jenkins_user_name }}"
    group: "{{ jenkins_user_group }}"
    shell: "{{ jenkins_user_shell }}"
    state: present
    comment: "Jenkins user"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_passphrase: "{{ jenkins_user_passphrase }}"
#  register: jenkins_slave_user
  tags:
    - provision-jenkins

- name: Get Jenkins user ssh public key
  slurp:
    src: "{{ jenkins_user_home + '/.ssh/id_rsa.pub' }}"
  register: jenkins_user_public_key
  tags:
    - provision-jenkins
  when: jenkins_slave_connection_type == 'ssh'

- name: Add Jenkins user ssh key to authorized keys
  authorized_key:
    user: "{{ jenkins_user_name }}"
    key: "{{ jenkins_user_public_key['content'] | b64decode }}"
  tags:
    - provision-jenkins
  when: jenkins_slave_connection_type == 'ssh'

- name: Include Ubuntu jenkins-slave role tasks
  include_tasks: Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'
  tags:
    - provision-jenkins-slave

- name: Include Darwin jenkins-slave role tasks
  include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - provision-jenkins-slave